### ISSUE TITLE
Provide a web-based implementation

### ISSUE THREAD

**Issue by ocean90** [WPSwitzerland/wordpress-de-ch#6]
During today's WordCamp Zurich Contributor Day we briefly discussed if a web-based solution for transforming a de_DE file to de_CH is possible. Not everyone is comfortable with command line tools, so just uploading a file and getting a transformed file back should help in getting more projects translated into de_CH.

Instead of running the bash script we probably have to convert the replacement commands in PHP (or JS).

If this works, we can also talk about a solution that can be integrated on translate.w.org directly.

**Comment by ocean90** [comment]
We could use the Gettext PHP library which allows to read PO files but also to create a new PO file after the replacements.

Extraction: https://github.com/oscarotero/Gettext#extractors
Generator: https://github.com/oscarotero/Gettext#generators

The library is also used by the WP-CLI i18n command.

cc: @swissspidy

**Comment by ocean90** [comment]
#7 is a first version, you can give it a try at https://po.dominikschilling.de/.

**Comment by nickw108** [comment]
Thank you so much Dominik, will play around with it asap.

**Comment by markhowellsmead** [comment]
Any news on this, @nickw108?

**Comment by nickw108** [comment]
What exactly do you mean? Dominik's web based implementation still works. We could (also) host it on https://wpswitzerland.ch/ if you think that makes sense, but I don't have access to that domain.

**Comment by markhowellsmead** [comment]
Can this issue be closed, then?

**Comment by nickw108** [comment]
Yes, I'll close it for now.
