### ISSUE TITLE
Swiss Time Format

### ISSUE THREAD

**Issue by nickw108** [WPSwitzerland/wordpress-de-ch#9]
I was notified by Marc Wieland that the Swiss time format is different than the German one https://de.wikipedia.org/wiki/Uhrzeit#Schweiz, i.e. `12.05` instead of `12:05`. We both "intuitively" used the German format in writing, but I guess we should change that in the official German (Switzerland) locale.  

**Instances of PHP time format `H:i` and `H:i:s` in various `.po` files:**
```` 
wp-content/languages via 🐘 v8.2.7 
➜ grep -R --include="*.po" "H:i" .

./de_CH_informal.po:msgid "F j, Y @ H:i:s"
./de_CH.po:msgid "F j, Y @ H:i:s"
./admin-de_CH.po:msgid "H:i"
./admin-de_CH.po:msgstr "H:i"
./admin-de_CH.po:msgid "Y-m-d H:i:s"
./admin-de_CH.po:msgid "j M @ H:i"
./admin-de_CH.po:msgid "M j, Y @ H:i"
./admin-de_CH_informal.po:msgid "H:i"
./admin-de_CH_informal.po:msgstr "H:i"
./admin-de_CH_informal.po:msgid "Y-m-d H:i:s"
./admin-de_CH_informal.po:msgid "j M @ H:i"
./admin-de_CH_informal.po:msgstr "j. M @ H:i"
./admin-de_CH_informal.po:msgid "M j, Y @ H:i"
````

Since we're using https://github.com/WPSwitzerland/wordpress-de-ch/blob/master/web/index.php to convert the de_DE .po files for de_CH via https://po.dominikschilling.de/ instead of manually translating everything, we need to add replacement of `H:i` with `H.i` in the code. 

I'm not so sure about replacing `H:i:s` with `H.i.s`, too though, since the Wikipedia article does not provide any Switzerland specific examples that also include seconds and it intuitively looks wrong. But that's what I thought about `H.i`, too.
So, I'm curious to hear your opinions or if this is not a matter of opinion, any references to official documents that define the right usage.

**Comment by swissspidy** [comment]
Well that just mentions the preferences of Bundeskanzlei (current version at https://www.bk.admin.ch/bk/de/home/dokumentation/sprachen/hilfsmittel-textredaktion/schreibweisungen.html)

> Die Schreibweisungen enthalten Schreib- und Formulierungsregeln für die amtlichen Texte des Bundes. Sie gelten insbesondere für Botschaften, Berichte und Erlasstexte.

That doesn't necessarily mean it's common for the rest of the country.

In my opinion, we should be using whatever format is most common in daily life.

If I go to 20min.ch or tagi.ch for example they use `H:i` too.

By the way, the PDF above mentions not using leading zeros. So `G` instead of `H`. But I am not seeing that in the wild either.

IMHO I would not change anything.

----

cc @marcwieland95 in case he wants to chime in here.

**Comment by martin8032** [comment]
I would prefer to stick with 12:05 as well. This makes it clear that we are talking about hours and minutes even when no other information is given. And it's also locial, since a decimal point is for decimals, and time is not based on the decimal system.

**Comment by marcwieland95** [comment]
For me, writing it with a dot isn't intuitive, but according to Wikipedia the correct way. Although as Pascal pointed out only for official government documents.

I just reached out to my former teacher to ask about the correct Swiss standards in typography. I'll keep you posted here.

**Comment by marcwieland95** [comment]
I did some research and got the information from a book that kind of sets the standards in Swiss typography.

My teacher also confirmed that with hours and minutes there's always a dot. Newspapers aren't doing a great job nowadays by sticking to standards, it's a bit wild west. She mentioned that NZZ used a proper proofreading years ago and was following the rules properly.

Meaning the typographically correct way would be: `G.i` and `G:i:s`.

Here the references:

![CleanShot 2024-04-25 at 22 24 12@2x](https://github.com/WPSwitzerland/wordpress-de-ch/assets/6168975/8075a5b5-6a02-4743-a81c-4e9f02537a32)
![CleanShot 2024-04-25 at 22 25 10@2x](https://github.com/WPSwitzerland/wordpress-de-ch/assets/6168975/f2e95ae1-d0b8-4dc4-88e6-44e5e1e70326)
![CleanShot 2024-04-25 at 22 25 42@2x](https://github.com/WPSwitzerland/wordpress-de-ch/assets/6168975/a305a02b-00f1-4504-abf3-c1dae32196c1)
![CleanShot 2024-04-25 at 22 28 16@2x](https://github.com/WPSwitzerland/wordpress-de-ch/assets/6168975/c435b1e5-5826-40a1-9ac5-ee5b9aec8b31)

**Comment by nickw108** [comment]
Thanks for your feedback. So I guess we we keep it exactly as it is 😅
